/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccueilRouteImport } from './routes/_authenticated/accueil'
import { Route as AuthenticatedMissionsRouteImport } from './routes/_authenticated/missions'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOpportunitesRouteImport } from './routes/_authenticated/opportunites'
import { Route as AuthenticatedPrestataireRouteImport } from './routes/_authenticated/prestataire'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedDemandesIndexRouteImport } from './routes/_authenticated/demandes.index'
import { Route as AuthenticatedDemandesIdRouteImport } from './routes/_authenticated/demandes.$id'
import { Route as AuthenticatedDemandesNouvelleRouteImport } from './routes/_authenticated/demandes.nouvelle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccueilRoute = AuthenticatedAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissionsRoute = AuthenticatedMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpportunitesRoute =
  AuthenticatedOpportunitesRouteImport.update({
    id: '/opportunites',
    path: '/opportunites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrestataireRoute =
  AuthenticatedPrestataireRouteImport.update({
    id: '/prestataire',
    path: '/prestataire',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandesIndexRoute =
  AuthenticatedDemandesIndexRouteImport.update({
    id: '/demandes/',
    path: '/demandes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandesIdRoute = AuthenticatedDemandesIdRouteImport.update({
  id: '/demandes/$id',
  path: '/demandes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandesNouvelleRoute =
  AuthenticatedDemandesNouvelleRouteImport.update({
    id: '/demandes/nouvelle',
    path: '/demandes/nouvelle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/opportunites': typeof AuthenticatedOpportunitesRoute
  '/prestataire': typeof AuthenticatedPrestataireRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/demandes/$id': typeof AuthenticatedDemandesIdRoute
  '/demandes/nouvelle': typeof AuthenticatedDemandesNouvelleRoute
  '/demandes/': typeof AuthenticatedDemandesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/opportunites': typeof AuthenticatedOpportunitesRoute
  '/prestataire': typeof AuthenticatedPrestataireRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/demandes/$id': typeof AuthenticatedDemandesIdRoute
  '/demandes/nouvelle': typeof AuthenticatedDemandesNouvelleRoute
  '/demandes': typeof AuthenticatedDemandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accueil': typeof AuthenticatedAccueilRoute
  '/_authenticated/missions': typeof AuthenticatedMissionsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/opportunites': typeof AuthenticatedOpportunitesRoute
  '/_authenticated/prestataire': typeof AuthenticatedPrestataireRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/demandes/$id': typeof AuthenticatedDemandesIdRoute
  '/_authenticated/demandes/nouvelle': typeof AuthenticatedDemandesNouvelleRoute
  '/_authenticated/demandes/': typeof AuthenticatedDemandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accueil'
    | '/missions'
    | '/notifications'
    | '/opportunites'
    | '/prestataire'
    | '/profil'
    | '/demandes/$id'
    | '/demandes/nouvelle'
    | '/demandes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accueil'
    | '/missions'
    | '/notifications'
    | '/opportunites'
    | '/prestataire'
    | '/profil'
    | '/demandes/$id'
    | '/demandes/nouvelle'
    | '/demandes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accueil'
    | '/_authenticated/missions'
    | '/_authenticated/notifications'
    | '/_authenticated/opportunites'
    | '/_authenticated/prestataire'
    | '/_authenticated/profil'
    | '/_authenticated/demandes/$id'
    | '/_authenticated/demandes/nouvelle'
    | '/_authenticated/demandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accueil': {
      id: '/_authenticated/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AuthenticatedAccueilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions': {
      id: '/_authenticated/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AuthenticatedMissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunites': {
      id: '/_authenticated/opportunites'
      path: '/opportunites'
      fullPath: '/opportunites'
      preLoaderRoute: typeof AuthenticatedOpportunitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prestataire': {
      id: '/_authenticated/prestataire'
      path: '/prestataire'
      fullPath: '/prestataire'
      preLoaderRoute: typeof AuthenticatedPrestataireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandes/': {
      id: '/_authenticated/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof AuthenticatedDemandesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandes/$id': {
      id: '/_authenticated/demandes/$id'
      path: '/demandes/$id'
      fullPath: '/demandes/$id'
      preLoaderRoute: typeof AuthenticatedDemandesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandes/nouvelle': {
      id: '/_authenticated/demandes/nouvelle'
      path: '/demandes/nouvelle'
      fullPath: '/demandes/nouvelle'
      preLoaderRoute: typeof AuthenticatedDemandesNouvelleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccueilRoute: typeof AuthenticatedAccueilRoute
  AuthenticatedMissionsRoute: typeof AuthenticatedMissionsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOpportunitesRoute: typeof AuthenticatedOpportunitesRoute
  AuthenticatedPrestataireRoute: typeof AuthenticatedPrestataireRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedDemandesIdRoute: typeof AuthenticatedDemandesIdRoute
  AuthenticatedDemandesNouvelleRoute: typeof AuthenticatedDemandesNouvelleRoute
  AuthenticatedDemandesIndexRoute: typeof AuthenticatedDemandesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccueilRoute: AuthenticatedAccueilRoute,
  AuthenticatedMissionsRoute: AuthenticatedMissionsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOpportunitesRoute: AuthenticatedOpportunitesRoute,
  AuthenticatedPrestataireRoute: AuthenticatedPrestataireRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedDemandesIdRoute: AuthenticatedDemandesIdRoute,
  AuthenticatedDemandesNouvelleRoute: AuthenticatedDemandesNouvelleRoute,
  AuthenticatedDemandesIndexRoute: AuthenticatedDemandesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
